# Generated by Django 2.2.17 on 2020-11-19 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 11, 19, 12, 38, 53, 553024, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
            ],
        ),
    ]
