# Generated by Django 2.2.17 on 2020-11-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20201119_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('page_number', models.IntegerField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
