# Generated by Django 2.2.17 on 2020-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='description',
            field=models.TextField(),
        ),
    ]
