# Generated by Django 2.2.17 on 2020-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20201121_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='sheets',
            field=models.ManyToManyField(blank=True, to='sheets.Sheet'),
        ),
    ]
