# Generated by Django 2.2.17 on 2020-11-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amout',
            new_name='total_amount',
        ),
    ]
